name: rlh_client
description: Worked location hours (rlh)

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod_client: 2.3.0
  serverpod_auth_client: 2.3.0
  serverpod_auth_email_flutter: 2.3.0
  serverpod_auth_shared_flutter: 2.3.0
  
